language: python
python:
  #- "2.6"
  - "2.7"
  #- "3.2"
  #- "3.3"
  #- "3.4"
  - "3.5"
  #- "3.5-dev"
  #- "nightly"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r docs_requirements.txt
  - pip install pep8
  - pip install flake8

# command to run tests
script:
  - flake8
  - ./run-uts.bash --no-color
  - sphinx-build -b html docs build
